import {
    Table,
    Modal,
    Menu,
    Input,
    Form,
    Card,
    Checkbox,
    Radio,
    Col,
    Row,
    Select,
    DatePicker,
    Steps,
    Switch,
    Button,
    List,
    Tree,
    Cascader,
    Space,
    Tooltip,
    InputNumber,
    Divider,
    Empty,
    Image,
    Popconfirm,
    Pagination,
    Spin,
    TreeSelect,
    PageHeader,
    Descriptions,
    Drawer,
    Tabs,
    Carousel,
    Collapse,
    Upload,
    Transfer,
    Dropdown,
    Badge,
  } from 'ant-design-vue';
  import type { App } from 'vue';
  export function setupAntd(app: App<Element>) {
    app.component('ADescriptionsItem', Descriptions.Item);
  
    app
      .use(Button)
      .use(Form)
      .use(Input)
      .use(Modal)
      .use(Table)
      .use(Menu)
      .use(Card)
      .use(Checkbox)
      .use(Radio)
      .use(Col)
      .use(Row)
      .use(Select)
      .use(DatePicker)
      .use(Steps)
      .use(Switch)
      .use(List)
      .use(Tree)
      .use(Cascader)
      .use(Space)
      .use(Tooltip)
      .use(Divider)
      .use(Empty)
      .use(Image)
      .use(Popconfirm)
      .use(Pagination)
      .use(Spin)
      .use(TreeSelect)
      .use(InputNumber)
      .use(PageHeader)
      .use(Drawer)
      .use(Collapse)
      .use(Tabs)
      .use(Carousel)
      .use(Upload)
      .use(Dropdown)
      .use(Transfer)
      .use(Badge)
      .use(Descriptions);
  }
  